name: leaf
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  image: ^3.0.2
  tflite_v2: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0



flutter:
  assets:
    - assets/
    - assets/leaf_disease_model.tflite
    - assets/model_unquant.tflite
    - assets/labels.txt
  uses-material-design: true
